# Generated by Django 4.0.3 on 2022-05-25 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halls', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('KH', 'KINGDOM HALL'), ('MH', 'MISSION HALL')], max_length=2)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SC', 'SELF CONTAINED'), ('SR', 'SINGLE ROOM'), ('DA', 'DORMITORY BUNKS (80)'), ('DB', 'DORMITORY BUNKS (40)'), ('DC', 'DORMITORY BUNKS (40)')], max_length=2)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('surName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('telephone1', models.CharField(max_length=250)),
                ('telephone2', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_address', models.CharField(max_length=250)),
                ('contact_phone', models.CharField(max_length=250)),
                ('relationship', models.CharField(max_length=250)),
                ('idCard', models.ImageField(upload_to='images/id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_photo', models.ImageField(upload_to='images/confirm')),
                ('account_name', models.CharField(max_length=240)),
                ('account_number', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=250)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.halls')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
